AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template for deploying Ember to S3 and CloudFront.
  Based on https://github.com/kaliber5/ember-cli-deploy-cloudformation/blob/master/examples/S3%2BCloudFront/cfn.yaml
Parameters:
  WebsiteHostname:
    Description: Hostname of the website.
    Type: String
  DomainName:
    Description: Domain name of the CDN.
    Type: String
  CFCertificate:
    Description: Existing ACM Certificate ARN for CloudFront.
    Type: String
Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${AssetsBucket}/*'
            Principal: '*'
          - Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !GetAtt AssetsBucket.Arn
            Principal: '*'
  AssetsCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt AssetsBucket.DomainName
            Id: AssetsBucket
            S3OriginConfig: {}
        Enabled: true
        HttpVersion: http2
        Aliases:
          - !Join ['', [!Ref WebsiteHostname, '.', !Ref DomainName]]
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: AssetsBucket
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref CFCertificate
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/_empty.html"
        DefaultRootObject: "index.html"
  DNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join
        - ''
        - - !Ref DomainName
          - .
      Comment: CNAME redirect custom name to CloudFront distribution
      Name: !Join ['', [!Ref WebsiteHostname, '.', !Ref DomainName]]
      AliasTarget:
        DNSName: !GetAtt AssetsCDN.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2"
      Type: A

Outputs:
  AssetsBucket:
    Value: !Ref AssetsBucket
  CloudFrontDistribution:
    Value: !Ref AssetsCDN
  CloudFrontDomainName:
    Value: !GetAtt AssetsCDN.DomainName
